// src/lib/packages/mockData.ts
import { MedicalPackage } from "./types";

export const DESTINATIONS = [
  "Istanbul, TR",
  "Antalya, TR",
  "Warsaw, PL",
  "Bangkok, TH",
  "Mexico City, MX",
  "Munich, DE",
  "Barcelona, ES",
];

export const PACKAGES: MedicalPackage[] = [
  {
    id: "p1",
    title: "Dental Implants Package – Istanbul",
    clinicName: "International Dental Clinic",
    destination: "Istanbul, TR",
    treatmentCategory: "Dental",
    inclusions: ["hotel", "transfers", "german_support", "aftercare"],
    verifications: ["meddiscover_verified", "jci"],
    satisfactionPct: 98,
    hotelStars: 5,
    priceFromEur: 1890,
    bullets: ["4 Titanium Implants", "5-Star Hotel (4 Nights)", "Airport-Clinic Transfers"],
    images: [{ alt: "Clinic" }, { alt: "Hotel" }, { alt: "City" }],
    spotlight: true,
  },
  {
    id: "p2",
    title: "Hair Transplant Package – Antalya",
    clinicName: "Aegean Aesthetics Center",
    destination: "Antalya, TR",
    treatmentCategory: "Cosmetic",
    inclusions: ["hotel", "transfers"],
    verifications: ["meddiscover_verified", "iso"],
    satisfactionPct: 95,
    hotelStars: 4,
    priceFromEur: 1550,
    bullets: ["FUE Technique", "4-Star Hotel (3 Nights)", "VIP Transfers"],
    images: [{ alt: "Clinic" }, { alt: "Hotel" }, { alt: "City" }],
  },
  {
    id: "p3",
    title: "IVF Package – Warsaw",
    clinicName: "Nova Fertility Clinic",
    destination: "Warsaw, PL",
    treatmentCategory: "IVF",
    inclusions: ["aftercare"],
    verifications: ["jci"],
    satisfactionPct: 92,
    hotelStars: 4,
    priceFromEur: 4200,
    bullets: ["IVF Cycle Included", "Aftercare Plan", "Coordinator Support"],
    images: [{ alt: "Clinic" }, { alt: "Hotel" }, { alt: "City" }],
  },
  {
    id: "p4",
    title: "Orthopedic Care Package – Munich",
    clinicName: "OrthoMed Center",
    destination: "Munich, DE",
    treatmentCategory: "Orthopedics",
    inclusions: ["aftercare", "german_support"],
    verifications: ["iso"],
    satisfactionPct: 90,
    hotelStars: 4,
    priceFromEur: 7200,
    bullets: ["Specialist Consultation", "Recovery Guidance", "Aftercare Included"],
    images: [{ alt: "Clinic" }, { alt: "Hotel" }, { alt: "City" }],
  },
  {
    id: "p5",
    title: "Weight Loss Surgery Package – Bangkok",
    clinicName: "Siam Bariatric Institute",
    destination: "Bangkok, TH",
    treatmentCategory: "Weight Loss",
    inclusions: ["hotel", "transfers", "aftercare"],
    verifications: ["jci"],
    satisfactionPct: 94,
    hotelStars: 5,
    priceFromEur: 6800,
    bullets: ["Procedure Included", "5-Star Hotel (5 Nights)", "Aftercare Plan"],
    images: [{ alt: "Clinic" }, { alt: "Hotel" }, { alt: "City" }],
  },
];
